spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix:
      - classpath:/templates/

  datasource:
    url: jdbc:mysql://localhost:3306/pdr?useUnicode=true&characterEncoding=utf8
    username: example
    password: example

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database: mysql
#    show-sql: true
